web:
    build: .
    ports:
        - "8080:8080"
        - "3000:3000"
    net: "host"
    volumes:
        - .:/usr/src/app
    links:
        - cockroachdb
cockroachdb:
    build: .
    dockerfile: Dockerfile-cockroach
    ports:
        - "5432:8080"
